### ISSUE TITLE
页面出现多个id

### ISSUE THREAD

**Issue by amyhuangxbd** [alitajs/DynamicForm#164]
![image](https://user-images.githubusercontent.com/4026511/117629582-e63a3e00-b1ac-11eb-9b05-36e8a6103ca3.png)

**Comment by hang1017** [comment]
fieldProps 设置为单一值

**Comment by amyhuangxbd** [comment]
> fieldProps 设置为单一值

设置的是单一值哦，
input-title 有个id， vertical-input也有个同样id，应该是bug

**Comment by hang1017** [comment]
v2.2.0 版本请验证

**Comment by hang1017** [comment]
还有任何问题若未及时回复可以加钉钉群：21924668
