### ISSUE TITLE
标题超长换行之后, coverStyle选择textAlign = right不生效

### ISSUE THREAD

**Issue by Renderz** [alitajs/DynamicForm#189]
.alitajs-dform-vertical-picker .am-list-extra {
   text-align: left !important
}

**Comment by hang1017** [comment]
@Renderz 好的。今天内会看下问题，发个新包。

**Comment by hang1017** [comment]
@Renderz  没发现这个bug。
![image](https://user-images.githubusercontent.com/48704410/129131847-6a88f4c6-a2eb-4958-8488-83b86fd4f91b.png)
![image](https://user-images.githubusercontent.com/48704410/129131874-dfa37cdd-c7aa-40b2-a4f7-3104f51a00f9.png)

**Comment by Renderz** [comment]
> @Renderz 没发现这个bug。
> ![image](https://user-images.githubusercontent.com/48704410/129131847-6a88f4c6-a2eb-4958-8488-83b86fd4f91b.png)
> ![image](https://user-images.githubusercontent.com/48704410/129131874-dfa37cdd-c7aa-40b2-a4f7-3104f51a00f9.png)

我等下开一个codesandbox出来. 我用的是
{
      type: "select",
      fieldProps: "select",
      required: true,
      title: "标题名称过长(超过14个字符自动换行)",
      data: [
        {
          label: "北京",
          value: "beijing"
        },
        {
          label: "上海",
          value: "shanghai"
        },
        {
          label: "福州",
          value: "fuzhou"
        }
      ]
    }

**Comment by hang1017** [comment]
@Renderz 单选改用picker 吧

**Comment by Renderz** [comment]
> @Renderz 单选改用picker 吧

确实可以了.

不过有个小小的疑问,  [栗子](https://codesandbox.io/s/cg9hq?module=/demo.tsx)里面
如果formsData只保留: 
```
{
      type: 'text',
      fieldProps: 'username',
      required: true,
      placeholder: '输入项居左',
      title: '用户名',
      clear: true,
      subTitle: subTitle(),
      coverStyle: {
        textAlign: 'left',
        color: 'blue',
      },
      onClick: () => {
        console.log();
      },
    },
```
会显示
**Object literal may only specify known properties, and 'clear' does not exist in type 'IFormItemProps'**

**Comment by hang1017** [comment]
@Renderz v2 的版本会存在类型定义有误的问题，可以先用截图中的方法解决。v3 版本会优化该问题。
![image](https://user-images.githubusercontent.com/48704410/129133654-c95638e5-9142-4592-85ec-7aa7d153a10d.png)

**Comment by Renderz** [comment]
> @Renderz v2 的版本会存在类型定义有误的问题，可以先用截图中的方法解决。v3 版本会优化该问题。

赞!
