### ISSUE TITLE
AddressPicker组件使用疑问

### ISSUE THREAD

**Issue by zk8080** [alitajs/DynamicForm#216]
AddressPicker组件在首次选择地址后，再次点击地址进行选择操作，修改地址后点击取消，此时再次进入选择地址弹窗会保留上次选择地址数据，导致已选择数据和弹窗中数据不一致。官方的V2和V3版本中的Demo都有这个问题，请问使用时如何能解决这个问题？

**Comment by DIYCCC** [comment]
This has been processed in V3.2.4

**Comment by zk8080** [comment]
刚才试了下官方的Demo，再次打开的弹窗中标题确实和已选择数据一致，但是data还保留了上次修改地址后的数据，导致弹窗中的标题和地址列表的数据不一致。是否可以在弹窗打开后重新调用一次onChangeLevel事件，保持数据一致。
另外，我现在使用的是V2版本的，是否可以直接升级到V3版本。有什么注意事项么

**Comment by DIYCCC** [comment]
1.请给复现demo或者截图
2.可以升级

**Comment by zk8080** [comment]
操作Gif如下，最后操作完成后，鼓楼区下的地址列表依然为上次修改后未确认的北京市数据。
![Demo](https://cdn.mobilemd.cn/tos-design/demo.gif)

**Comment by zk8080** [comment]
请问这个有修复计划么

**Comment by hang1017** [comment]
有，这两天正在处理中，根据修复情况看下是否需要回退到提 issues 的版本，或者修复该问题，发布新版本。
发新版本会通知您。

**Comment by DIYCCC** [comment]
使用3.3.0-alpha.1这个版本看看，demo代码在3.3.x分子。

**Comment by DIYCCC** [comment]
https://github.com/alitajs/DynamicForm/blob/v3.3.x/src/components/AddressPicker/demo/index.tsx

**Comment by zk8080** [comment]
> 使用3.3.0-alpha.1这个版本看看，demo代码在3.3.x分子。

试了下没有问题了，感谢修复🙏。
